# Generated by Django 5.0.6 on 2024-05-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_app', '0002_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
